name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build_linux:
    name: Build binaries - manylinux_2_28_x86_64
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - name: install system dependencies
      run: dnf install -y openssh-clients
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    # Get a patched version of JuliaC
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target install --config Release
    - name: trim out unnecessary artifacts
      run: cd build/install/share/julia/artifacts && rm -rf $(julia --project=${{ github.workspace }} ${{ github.workspace }}/scripts/trim_cuda_artifacts.jl)
    - name: tar output
      run: cd build/install && tar -czf ../../libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"

  build_windows:
    name: Build binaries - windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - name: Windows SSH Key workarounds # A horrible hack, see https://github.com/webfactory/ssh-agent/issues/148#issuecomment-2602109257
      shell: bash
      run: |
        mkdir -p $HOME/.ssh
        cat << EOF > $HOME/.ssh/known_hosts
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        EOF
    - name: Set julia git
      run: echo "JULIA_PKG_USE_CLI_GIT=true" | Out-File -FilePath $env:GITHUB_ENV -Append
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "PATH=$HOME\.julia\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: pwsh
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target INSTALL --config Release
    - name: trim out unnecessary artifacts
      run: |
        function quiet_rm($items)
        {
          foreach($item in $items)
          {
            if (Test-Path $item)
            {
              echo "  Removing $item"
              Remove-Item $item  -r -force
            }
          }
        }
        cd build/install/share/julia/artifacts && quiet_rm $(julia --project=${{ github.workspace }} ${{ github.workspace }}/scripts/trim_cuda_artifacts.jl)
    - name: tar output
      run: |
        cd build\install && tar.exe -czf ..\..\libMad-windows-x86_64-${{ github.ref_name }}.tar.gz *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-windows-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-windows-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"

  build_apple:
    name: Build binaries - macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target install --config Release
    - name: trim out unnecessary artifacts
      run: cd build/install/share/julia/artifacts && rm -rf $(julia --project=${{ github.workspace }} ${{ github.workspace }}/scripts/trim_cuda_artifacts.jl)
    - name: tar output
      run: |
        cd build/install && tar -czf ../../libMad-apple-aarch64-${{ github.ref_name }}.tar.gz *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-apple-aarch64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-apple-aarch64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"
